import type { EventItem, Member, ShopItem } from "./types";
import { tierFromXp } from "./xp";

const xp = 1820;

export const currentMember: Member = {
  id: "IIC-026-00427",
  name: "AKARI TANIGUCHI",
  handle: "@akari.t",
  avatar: "/avatars/akari.svg",
  memberSince: "2025-09-12",
  tier: tierFromXp(xp),
  xp,
  stats: {
    attended: 14,
    hours: 47,
    streak: 6,
  },
};

export const events: EventItem[] = [
  {
    id: "bullish",
    code: "BUL.026.05",
    title: "Bullish",
    date: "2026-05-16T10:00:00",
    location: "MAIN HALL",
    xpReward: 240,
    cover: "/gallery/01.png",
    status: "attended",
  },
  {
    id: "anveshana-3",
    code: "ANV.026.03",
    title: "Anveshana 3.0",
    date: "2026-03-14T10:00:00",
    location: "AUDITORIUM",
    xpReward: 280,
    cover: "/gallery/02.png",
    status: "attended",
  },
  {
    id: "overclock",
    code: "OVC.025.09",
    title: "Overclock",
    date: "2025-09-20T10:00:00",
    location: "MAKER LAB",
    xpReward: 220,
    cover: "/gallery/03.png",
    status: "attended",
  },
  {
    id: "pitch-off",
    code: "PTO.025.05",
    title: "Pitch Off",
    date: "2025-05-17T10:00:00",
    location: "AUDITORIUM",
    xpReward: 200,
    cover: "/gallery/04.png",
    status: "attended",
  },
  {
    id: "anveshana-25",
    code: "ANV.025.03",
    title: "Anveshana '25",
    date: "2025-03-15T10:00:00",
    location: "MAIN HALL",
    xpReward: 260,
    cover: "/gallery/05.png",
    status: "attended",
  },
];

export const shopItems: ShopItem[] = [
  {
    id: "shp-001",
    sku: "FN-R542",
    name: "Field Notebook R542",
    subtitleJa: "フィールドノート",
    image: "/shop/notebook.svg",
    xpPrice: 200,
    tierRequired: "INITIATE",
    stock: 42,
  },
  {
    id: "shp-002",
    sku: "ST-IIC1",
    name: "IIC Sticker Pack",
    subtitleJa: "ステッカー.セット",
    image: "/shop/stickers.svg",
    xpPrice: 80,
    tierRequired: "INITIATE",
    stock: 99,
  },
  {
    id: "shp-003",
    sku: "CH-COIL",
    name: "Coil Hoodie",
    subtitleJa: "コイル.フーディ",
    image: "/shop/hoodie.svg",
    xpPrice: 1200,
    tierRequired: "ENGINEER",
    stock: 12,
  },
  {
    id: "shp-004",
    sku: "WP-Q3",
    name: "Workshop Pass — Q3",
    subtitleJa: "ワークショップ.パス",
    image: "/shop/pass.svg",
    xpPrice: 900,
    tierRequired: "ENGINEER",
    stock: 24,
  },
  {
    id: "shp-005",
    sku: "MH-01",
    name: "Mentor Hour",
    subtitleJa: "メンター.アワー",
    image: "/shop/mentor.svg",
    xpPrice: 1400,
    tierRequired: "ENGINEER",
    stock: 8,
  },
  {
    id: "shp-006",
    sku: "PV-2026",
    name: "Patent Filing Voucher",
    subtitleJa: "特許.バウチャー",
    image: "/shop/voucher.svg",
    xpPrice: 2600,
    tierRequired: "ARCHITECT",
    stock: 4,
  },
  {
    id: "shp-007",
    sku: "LK-LAB",
    name: "Lab Keycard — Tier A",
    subtitleJa: "ラボ.キーカード",
    image: "/shop/keycard.svg",
    xpPrice: 3000,
    tierRequired: "ARCHITECT",
    stock: 6,
  },
  {
    id: "shp-008",
    sku: "FR-INC",
    name: "Founder Incubation Slot",
    subtitleJa: "創業.スロット",
    image: "/shop/incubate.svg",
    xpPrice: 4200,
    tierRequired: "ORACLE",
    stock: 2,
  },
  {
    id: "shp-009",
    sku: "OR-KEY",
    name: "Oracle Access Key",
    subtitleJa: "オラクル.アクセス",
    image: "/shop/oracle.svg",
    xpPrice: 5000,
    tierRequired: "ORACLE",
    stock: 1,
  },
];
