import type { EventItem, Member, ShopItem } from "./types";
import { tierFromXp } from "./xp";

const xp = 1820;

export const currentMember: Member = {
  id: "IIC-026-00427",
  name: "AKARI TANIGUCHI",
  handle: "@akari.t",
  avatar: "/avatars/akari.svg",
  memberSince: "2025-09-12",
  tier: tierFromXp(xp),
  xp,
  stats: {
    attended: 14,
    hours: 47,
    streak: 6,
  },
};

export const events: EventItem[] = [
  {
    id: "evt-001",
    code: "IDE.026.02",
    title: "Ideathon 026.02",
    subtitleJa: "アイデアソン",
    date: "2026-02-08T10:00:00",
    location: "BLOCK A · STUDIO 3",
    xpReward: 220,
    cover: "/events/ideathon.svg",
    status: "attended",
  },
  {
    id: "evt-002",
    code: "PAT.026.01",
    title: "Patent Clinic",
    subtitleJa: "特許クリニック",
    date: "2026-01-22T14:00:00",
    location: "LAB · 02F",
    xpReward: 140,
    cover: "/events/patent.svg",
    status: "attended",
  },
  {
    id: "evt-003",
    code: "SPR.025.12",
    title: "Startup Sprint Vol.3",
    subtitleJa: "スタートアップ.スプリント",
    date: "2025-12-04T09:00:00",
    location: "MAIN HALL",
    xpReward: 360,
    cover: "/events/sprint.svg",
    status: "attended",
  },
  {
    id: "evt-004",
    code: "FXF.025.11",
    title: "Faculty x Founders",
    subtitleJa: "教員 × 創業者",
    date: "2025-11-18T16:00:00",
    location: "AUDITORIUM",
    xpReward: 180,
    cover: "/events/fxf.svg",
    status: "attended",
  },
  {
    id: "evt-005",
    code: "HHK.026.05",
    title: "Hardware Hack 48H",
    subtitleJa: "ハードウェア.ハック",
    date: "2026-05-30T09:00:00",
    location: "MAKER LAB",
    xpReward: 480,
    cover: "/events/hardware.svg",
    status: "upcoming",
  },
  {
    id: "evt-006",
    code: "MTR.026.06",
    title: "Mentor Roundtable",
    subtitleJa: "メンター.ラウンド",
    date: "2026-06-12T17:30:00",
    location: "BLOCK B · ROOM 4",
    xpReward: 160,
    cover: "/events/mentor.svg",
    status: "upcoming",
  },
  {
    id: "evt-007",
    code: "DMO.026.06",
    title: "Demo Day Q2",
    subtitleJa: "デモ.デイ",
    date: "2026-06-26T18:00:00",
    location: "MAIN HALL",
    xpReward: 320,
    cover: "/events/demo.svg",
    status: "upcoming",
  },
  {
    id: "evt-008",
    code: "AIW.026.07",
    title: "AI Workshop — Agents",
    subtitleJa: "AIワークショップ",
    date: "2026-07-09T13:00:00",
    location: "LAB · 03F",
    xpReward: 240,
    cover: "/events/ai.svg",
    status: "upcoming",
  },
];

export const shopItems: ShopItem[] = [
  {
    id: "shp-001",
    sku: "FN-R542",
    name: "Field Notebook R542",
    subtitleJa: "フィールドノート",
    image: "/shop/notebook.svg",
    xpPrice: 200,
    tierRequired: "INITIATE",
    stock: 42,
  },
  {
    id: "shp-002",
    sku: "ST-IIC1",
    name: "IIC Sticker Pack",
    subtitleJa: "ステッカー.セット",
    image: "/shop/stickers.svg",
    xpPrice: 80,
    tierRequired: "INITIATE",
    stock: 99,
  },
  {
    id: "shp-003",
    sku: "CH-COIL",
    name: "Coil Hoodie",
    subtitleJa: "コイル.フーディ",
    image: "/shop/hoodie.svg",
    xpPrice: 1200,
    tierRequired: "ENGINEER",
    stock: 12,
  },
  {
    id: "shp-004",
    sku: "WP-Q3",
    name: "Workshop Pass — Q3",
    subtitleJa: "ワークショップ.パス",
    image: "/shop/pass.svg",
    xpPrice: 900,
    tierRequired: "ENGINEER",
    stock: 24,
  },
  {
    id: "shp-005",
    sku: "MH-01",
    name: "Mentor Hour",
    subtitleJa: "メンター.アワー",
    image: "/shop/mentor.svg",
    xpPrice: 1400,
    tierRequired: "ENGINEER",
    stock: 8,
  },
  {
    id: "shp-006",
    sku: "PV-2026",
    name: "Patent Filing Voucher",
    subtitleJa: "特許.バウチャー",
    image: "/shop/voucher.svg",
    xpPrice: 2600,
    tierRequired: "ARCHITECT",
    stock: 4,
  },
  {
    id: "shp-007",
    sku: "LK-LAB",
    name: "Lab Keycard — Tier A",
    subtitleJa: "ラボ.キーカード",
    image: "/shop/keycard.svg",
    xpPrice: 3000,
    tierRequired: "ARCHITECT",
    stock: 6,
  },
  {
    id: "shp-008",
    sku: "FR-INC",
    name: "Founder Incubation Slot",
    subtitleJa: "創業.スロット",
    image: "/shop/incubate.svg",
    xpPrice: 4200,
    tierRequired: "ORACLE",
    stock: 2,
  },
  {
    id: "shp-009",
    sku: "OR-KEY",
    name: "Oracle Access Key",
    subtitleJa: "オラクル.アクセス",
    image: "/shop/oracle.svg",
    xpPrice: 5000,
    tierRequired: "ORACLE",
    stock: 1,
  },
];
